### ISSUE TITLE
Single party POL covenant

### ISSUE THREAD

**Issue by bekauz** [timewave-computer/covenants#104]

**Comment by uditvira** [comment]
Priority for this depends on which audit dates we get:
1. Scenario 1: We get a single date for v2 in late December or January 
- We drop the single party POL
- We do all the two party work + Osmosis integration
2. Scenario 2: We get two dates (one in December and the second in the 2024)
- We deliver single party POL + two party work in first audit
- We deliver osmosis integration in second audit
