### ISSUE TITLE
look into astroport pool pair types

### ISSUE THREAD

**Issue by bekauz** [timewave-computer/covenants#120]
Following up on the discussion on https://github.com/timewave-computer/covenants/pull/119#discussion_r1373022378:

Look into whether different pool pair types (stable, xyk, custom, ...) could affect this in some unexpected way.

**Comment by uditvira** [comment]
Main questions for this are:
- How do migrate pool types?
- How are prices calculated for each pool type?
- Is there a common abstracted interface we can use? In what ways are the interactions with the pools different?
