### ISSUE TITLE
ibc forwarder hardcoded ica fees

### ISSUE THREAD

**Issue by bekauz** [timewave-computer/covenants#148]
right now, ibc-forwarder passes some arguments by hardcoding them:

```rust
    let register_fee: Option<Vec<Coin>> = Some(vec![coin(1000001, "untrn")]);
```

let's get rid of that, as we do not know if this value will remain valid forever. either find a way to query the param onchain, or pass it as an argument during instantiation.

**Comment by Art3miX** [comment]
Should be done in single party pol v2
