### ISSUE TITLE
set up code migration tests

### ISSUE THREAD

**Issue by bekauz** [timewave-computer/covenants#180]
lets set up tests to simulate hypothetical situations where code migration would be needed to recover the funds from any contract. this will likely involve extending contracts with a new method that would recover the funds to a specified address, migrating the contract, and asserting that everything goes well.

**Comment by uditvira** [comment]
Can we please make a list of which tests you completed?

**Comment by uditvira** [comment]
@stiiifff could you please split this up into two issues, one for milestone 1 and one for milestone 2

**Comment by stiiifff** [comment]
Replaced by https://github.com/timewave-computer/internal-board/issues/30 and https://github.com/timewave-computer/covenants/issues/193
