### ISSUE TITLE
pull `CONTRACT_NAME` and `CONTRACT_VERSION` consts from cargo file via env

### ISSUE THREAD

**Issue by bekauz** [timewave-computer/covenants#209]

**Comment by stiiifff** [comment]
Licenses should be assigned to Timewave.

**Comment by stiiifff** [comment]
@bekauz this was fixed by this [commit](https://github.com/timewave-computer/covenants/commit/cab7dbacdd978c980bc60a4b203aa33534a2864d) right ? Can we close it ?

**Comment by stiiifff** [comment]
Closed by #216
