### ISSUE TITLE
Upgrade to latest cosmwasm/optimizer v0.16.0

### ISSUE THREAD

**Issue by stiiifff** [timewave-computer/covenants#297]
The project is using a year old version of the `cosmwasm/workspace-optimizer` tool for test & production builds of the contracts.
Version v0.16.0 has been recently released (see [changelog](https://github.com/CosmWasm/optimizer/blob/main/CHANGELOG.md)). We probably should upgrade to benefit from latest Rust compiler enhancements.
Also the `cosmwasm/workspace-optimizer` image has been deprecated, we should now use `cosmwasm/optimizer` instead (and it only takes 1 contract project at a time, so the optimize script has to be updated).

**Comment by bekauz** [comment]
covered by #296 ?

**Comment by bekauz** [comment]
closed by #296
